### ISSUE TITLE
Once install, how do you connect to the local device?

### ISSUE THREAD

**Issue by resistdesign** [MasterDevX/Termux-ADB#1]
Once you can run adb in termux, how do you connect to the device you're running on?

**Comment by Amrangithub** [comment]
tqvm

**Comment by MasterDevX** [comment]
> Once you can run adb in termux, how do you connect to the device you're running on?

You need to turn on 'ADB over network' and then execute this:
```adb connect localhost```

**Comment by RenatoLopes771** [comment]
> > Once you can run adb in termux, how do you connect to the device you're running on?
> 
> You need to turn on 'ADB over network' and then execute this:
> `adb connect localhost`

But which termux command enables ADB over network?

**Comment by MasterDevX** [comment]
@underlineGalaxy You can read this thread on StackOverflow to get some instructions.
https://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp

**Comment by SufieCruise** [comment]
> > > Once you can run adb in termux, how do you connect to the device you're running on?
> > 
> > 
> > You need to turn on 'ADB over network' and then execute this:
> > `adb connect localhost`
> 
> But which termux command enables ADB over network?

I'm having the same problem when i execute the localhost command it prints connection refused.
how can I fix this?
