### ISSUE TITLE
Fastboot issue

### ISSUE THREAD

**Issue by ghost** [MasterDevX/Termux-ADB#12]
The Error is -
$ fastboot
fastboot: usage: no command 

I am Enclosing my architecture info.

Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               0
Model name:          Cortex-A53
Stepping:            r0p0
CPU max MHz:         1209.6000
CPU min MHz:         200.0000
BogoMIPS:            38.40
Flags:               swp half thumb fastmu
                     lt vfp edsp neon vfpv
                     3 tls vfpv4 idiva idi
                     vt vfpd32 evtstrm

**Comment by Alexei1981** [comment]
fastboot --help

**Comment by MasterDevX** [comment]
@Gagan027 Yeah, you haven't executed any fastboot command.
See usage by running ```fastboot --help``` as @Alexei1981 suggested.
