### ISSUE TITLE
Installed in system root

### ISSUE THREAD

**Issue by palmuse** [MasterDevX/Termux-ADB#14]
I installed this in Termux then moved it to System since I am a root user on one of my devices. I did this to enable using my routed device as a "PC" via USB on my non rooted daily device. Everything is working as expected except I did not set up the adbkey so it does not hold the connection permission.

I think all I need to do is set this up to finish my setup. The question I have is where to put the adbkey files.

I know that for Termux they are placed in $HOME/adbfiles/. If I mirror this in root/adbfiles/, will it work? Or is there a better way to do this?

**Comment by MasterDevX** [comment]
I think it would be better if you put keys in the directory you can access from non-root user.
For example, you can store them in your internal storage, or if you don`t want this to be among your personal files, then why not to place it in /data/local/tmp/adbfiles :grin: 
And yep, don't forget to edit paths in the wrapper script.
