### ISSUE TITLE
no devices/emulators found

### ISSUE THREAD

**Issue by zidekuls** [MasterDevX/Termux-ADB#16]
Hi, i run 'adb shell', and the error message as title occured.

**Comment by MasterDevX** [comment]
Hello there, see https://github.com/MasterDevX/Termux-ADB/issues/7 or https://github.com/MasterDevX/Termux-ADB/issues/1 for the solution.

**Comment by Safuvanibru123** [comment]
error no devices/emulators found

**Comment by Safuvanibru123** [comment]
error no devices/emulators found
