### ISSUE TITLE
> ```adb shell

### ISSUE THREAD

**Issue by piagzaa24** [MasterDevX/Termux-ADB#19]
> ```
> $ adb shell
> error: device unauthorized.
> This adb server's $ADB_VENDOR_KEYS is not set
> Try 'adb kill-server' if that seems wrong.
> Otherwise check for a confirmation dialog on your device.
> ```

_Originally posted by @piagzaa24 in https://github.com/MasterDevX/Termux-ADB/issues/13#issuecomment-618136794_

**Comment by MasterDevX** [comment]
Why are you opening a new issue if you see this problem has been already reported in another issue?
Closing as duplicate, follow https://github.com/MasterDevX/Termux-ADB/issues/13 to stay aware.
