### ISSUE TITLE
Adb shell command not working

### ISSUE THREAD

**Issue by JosiasAurel** [MasterDevX/Termux-ADB#20]
When I open termux (after installing the repositories scripts and adb) and type
```shell
adb shell
```
I get this log and the terminal is back
```shell

* daemon not running. starting it now at tcp:5038 *
* daemon started successfully *
error: no devices/emulators found
```

Any advice ?

**Comment by MasterDevX** [comment]
Hey, you need to connect to your local device to work with ADB shell, see https://github.com/MasterDevX/Termux-ADB/issues/1 or https://github.com/MasterDevX/Termux-ADB/issues/7 for more info.
