### ISSUE TITLE
Wget issue 

### ISSUE THREAD

**Issue by Mokh03** [MasterDevX/Termux-ADB#22]
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget

**Comment by MasterDevX** [comment]
It is Wget, not ADB issue. Since Wget is part of termux-packages repository, I recommend you to create an issue here: https://github.com/termux/termux-packages/tree/master/packages
