### ISSUE TITLE
Device Not Found 

### ISSUE THREAD

**Issue by mnuddindev** [MasterDevX/Termux-ADB#25]
Hey sir,
I want to root my Phone During lockdown no cyber Cafe is open. But i really need root permission on my device i have two mobiles one is android 5 and other one is 7.0 i installed adb on android 5 and connected another device with usb and otg to android 5 and i tried to run "adb devices" its print nothing and when i tried to run "fastboot flash recovery recovery.img" its showing "<Waiting for Device>" please help me. both device are not rooted. Please please please help me

**Comment by MasterDevX** [comment]
Hey, looks like you can't use fastboot this way, see https://github.com/MasterDevX/Termux-ADB/issues/9#issuecomment-524622945 for explanation.
