### ISSUE TITLE
nice its work in my termux

### ISSUE THREAD

**Issue by qiwiled** [MasterDevX/Termux-ADB#29]
i just try it on my termux with redmi 3s device dan realme 5 and the result is good,thanks for this script
![Screenshot_2020-08-02-05-26-56-31_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/44135803/89111544-123bcc80-d481-11ea-9f65-cbccc083524f.png)

**Comment by tutacat** [comment]
It won't work on local device unless you enable adb over tcp

**Comment by qiwiled** [comment]
its just for testing the adb server was running in my device but without OTG,i was using adb with OTG in my device,so succesfuly define the device

**Comment by MasterDevX** [comment]
@qiwiled You're welcome, thanks for using ;)
