### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by KindlyOnes** [MasterDevX/Termux-ADB#3]
* daemon not running. starting it now at tcp:5038 *

Thank you for your efforts. :)

**Comment by MasterDevX** [comment]
>     * daemon not running. starting it now at tcp:5038 *

There is no error, the message just tells you that ADB daemon was not started and it is starting.
ADB should work, check it :D

**Comment by farzanbehbudi** [comment]
> > ```
> > * daemon not running. starting it now at tcp:5038 *
> > ```
> 
> There is no error, the message just tells you that ADB daemon was not started and it is starting.
> ADB should work, check it :D


no not work bro i check it
