### ISSUE TITLE
I have a few questions!!!

### ISSUE THREAD

**Issue by binhpro2k5** [MasterDevX/Termux-ADB#30]
Can I use this tool without root and magisk?

**Comment by tutacat** [comment]
Termux does not require any rooting in the slightest

Just to use it for local device you have to enable adb over tcp (from another device, `adb tcp 5555`)
It works with usb connected device without doing anything

**Comment by romandev** [comment]
@tutacat, could you please explain how we can connect local device in more details?
I tried it as follows:
1. Connect my device to host PC
2. Run `adb tcpip 5555` command on Host PC
3. Run `adb connect localhost:5555` command via Termux on my device
4. But it doesn't work well on my environment

**Comment by romandev** [comment]
Self answer:
Ah, okay. It works well. I was confusing with another device.
Thanks!

**Comment by tutacat** [comment]
Should work with localhost, adb doesn't actually take the `:port` bit of an address, just uses the default (port 5555)

**Comment by MasterDevX** [comment]
> Can I use this tool without root and magisk?

Sure, you can.
