### ISSUE TITLE
error: no devices/emulators found

### ISSUE THREAD

**Issue by ghost** [MasterDevX/Termux-ADB#48]

**Comment by EnderGaming1458** [comment]
If you use android 11 or newer do this

Go to Developer Setting, If you not enable it, turn it by click the version number many time

Then go enable the Developer Setting

Then swipe until you got wireless debugging

Turn it on and click connect by pair


On Termux, do adb pair (your IP:your port)

Then enter code when the code printed on target device

Then connect it (adb connect (your ip:port) )

Done!

**Comment by TyraVex** [comment]
![IMG_20211121_223743](https://user-images.githubusercontent.com/34800546/142779909-82145f63-f0d7-4949-b33d-f9eea3c87479.jpg)
Adb pair isn't recognized even if my phone is running android 11

**Comment by EnderGaming1458** [comment]
Use Termux 0.117 Version, Then Do
pkg install android-tools

**Comment by EnderGaming1458** [comment]
Have a nice day!

**Comment by TyraVex** [comment]
Thank you it so much it's working!

**Comment by lolerprol** [comment]
tyra why i don't see any solution u said its working but i don't see the solution ._.

**Comment by TyraVex** [comment]
He deleted all his answers ._.

**Comment by TyraVex** [comment]
Use this instead https://play.google.com/store/apps/details?id=eu.sisik.hackendebug

**Comment by lolerprol** [comment]
> Use this instead https://play.google.com/store/apps/details?id=eu.sisik.hackendebug

ty

**Comment by tiagosiebler** [comment]
What was the solution to this, instead of using that alternative app?

**Comment by mutturajumashitti** [comment]
adb: no devices/emulators found

**Comment by TyraVex** [comment]
> adb: no devices/emulators found

Adb pair works again

**Comment by Pavis0247** [comment]
> Thank you it so much it's working!

Hey! What did you do ti solve the issue?

**Comment by TyraVex** [comment]
![Screenshot_2023-03-20-09-23-51-572_com android settings-edit](https://user-images.githubusercontent.com/34800546/226285407-cc9a7a73-5627-4bce-ba21-a032ba89570d.jpg)
![Screenshot_2023-03-20-09-27-25-125_com android settings-edit](https://user-images.githubusercontent.com/34800546/226285416-2a4072b9-19f2-4c23-a0e2-d5d3a1ebda08.jpg)

adb pair ip:port code
