### ISSUE TITLE
adb.bin: Bad Address!

### ISSUE THREAD

**Issue by PontusTideman** [MasterDevX/Termux-ADB#54]
Was following this guide: [https://www.ytechb.com/enable-color-filter-camera-on-oneplus-8-pro/](url)

And after I´ve installed the F-droid version and updated the packages I managed to install the scripts for the OP8 camera.
But when I try to run the ./camera all I´m getting is:

`$ ./camera
/data/data/com.termux/files/usr/bin/adb: line 7: /data/data/com.termux/files/usr/bin/adb.bin: Bad address
/data/data/com.termux/files/usr/bin/adb: line 7: /data/data/com.termux/files/usr/bin/adb.bin: Bad address
/data/data/com.termux/files/usr/bin/adb: line 7: /data/data/com.termux/files/usr/bin/adb.bin: Bad address
/data/data/com.termux/files/usr/bin/adb: line 7: /data/data/com.termux/files/usr/bin/adb.bin: Bad address
/data/data/com.termux/files/usr/bin/adb: line 7: /data/data/com.termux/files/usr/bin/adb.bin: Bad address
/data/data/com.termux/files/usr/bin/adb: line 7: /data/data/com.termux/files/usr/bin/adb.bin: Bad address`

**Comment by PontusTideman** [comment]
Scrap this, this is a duplicate of #49 !

**Comment by rexackermann** [comment]
Any solution to it yet ??
