### ISSUE TITLE
adb for ArchTermux

### ISSUE THREAD

**Issue by JeelsBoobz** [MasterDevX/Termux-ADB#6]
How to using adb fastboot with Arch Termux?
With pacman -S android-tools not detect

**Comment by MasterDevX** [comment]
@JeelsBoobz Try to download ADB binaries and put them into /bin directory of Arch.

**Comment by JeelsBoobz** [comment]
Device not detected, how to solved it?

**Comment by MasterDevX** [comment]
Replied in https://github.com/MasterDevX/Termux-ADB/issues/7
