### ISSUE TITLE
The fastboot can't use

### ISSUE THREAD

**Issue by SeimoDev** [MasterDevX/Termux-ADB#8]
If I use the fastboot,however,it must say"Segmentation fault",I can't  use anything fastboot,please help me

**Comment by MasterDevX** [comment]
So, ADB itself works and only fastboot returns "segmentation fault", right?

**Comment by SeimoDev** [comment]
> 那么，ADB本身是可行的，只有fastboot返回“分段错误”，对吧？

right

**Comment by MasterDevX** [comment]
Okay, can you execute ```lscpu``` and post output here?

**Comment by SeimoDev** [comment]
yeah
lscpu
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           2
Vendor ID:           ARM
Model:               0
Model name:          Cortex-A55
Stepping:            r1p0
CPU max MHz:         2200.0000
CPU min MHz:         774.0000
BogoMIPS:            26.00
Flags:               fp asimd evtstrm aes pmul
                     l sha1 sha2 crc32 atomics
                      fphp asimdhp

**Comment by MasterDevX** [comment]
Hmm, everything is okay with architecture. It might be something is messed up in Termux. So if you don't have any important files there, you can try to fully reinstall it (uninstall & install from Google Play).

**Comment by SeimoDev** [comment]
OK,thank you ,I will reinstall it.

**Comment by MasterDevX** [comment]
Okay, I'm not sure if it will solve the problem, but currently it is the only thing I can suggest you.

**Comment by SeimoDev** [comment]
Solved, thank you
