### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by SeimoDev** [MasterDevX/Termux-ADB#9]
My phone can't boot now, I want to use fastboot  save it.I use otg to connect them.However, the device is not detected.

**Comment by MasterDevX** [comment]
Most devices can only work with phones connected via OTG as with media storage, so if your phone is not detected by fastboot it means your kernel does not support advanced USB connections like fastboot, ADB, etc. So you'll probably need to get a PC to unbrick your phone.

**Comment by MasterDevX** [comment]
BTW, what hapenned to your phone?

**Comment by SeimoDev** [comment]
I do some crazy things,And I can't boot the system and recovery😂😂

**Comment by MasterDevX** [comment]
@cldmh Lol, next time install TWRP (or CWM) and make backup before doing so xD

**Comment by SeimoDev** [comment]
I backed up, then a bad script formatted my data, I figured out how to brush the official system, but when I booted up
